# Generated by Django 5.0.6 on 2024-07-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservedtime",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
