# Generated by Django 5.0.6 on 2024-07-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_reservedtime_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservedtime",
            name="tg_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
