# Generated by Django 5.0.6 on 2024-09-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReservedTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date_time", models.DateTimeField(default=None)),
                ("reserve_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("user", models.CharField(blank=True, max_length=20, null=True)),
                ("tg_id", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
